# Generated by Django 3.1.4 on 2021-08-11 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_url', models.CharField(max_length=90)),
                ('module_name', models.CharField(choices=[('Administration', 'Administration'), ('Order', 'Order'), ('Inventory', 'Inventory')], max_length=50)),
                ('is_sub_menu', models.BooleanField(default=False)),
                ('sub_menu_name', models.CharField(blank=True, max_length=50, null=True)),
                ('menu_order', models.IntegerField(default=0)),
                ('menu_icon', models.CharField(blank=True, max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu List',
                'db_table': 'menu_list',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_action', models.BooleanField(default=False)),
                ('insert_action', models.BooleanField(default=False)),
                ('update_action', models.BooleanField(default=False)),
                ('delete_action', models.BooleanField(default=False)),
                ('permission_date', models.DateTimeField(auto_now_add=True)),
                ('permitted_by', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.menulist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'db_table': 'user_permission',
            },
        ),
    ]
