# Generated by Django 3.1.4 on 2021-01-13 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='bst',
        ),
        migrations.RemoveField(
            model_name='itemdetails',
            name='sku',
        ),
        migrations.AddField(
            model_name='barcode',
            name='bst',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barcode',
            name='sku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
