# Generated by Django 3.1.4 on 2021-01-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0002_auto_20210114_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='bst',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='sku',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
