# Generated by Django 3.1.4 on 2021-01-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0004_barcode_generate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='generate_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
