# Generated by Django 3.1.4 on 2021-01-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0005_auto_20210129_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='bst',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='barcode',
            name='sku',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
