# Generated by Django 3.1.4 on 2021-02-02 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pre_order', '0006_auto_20210130_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='checked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_order_checked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_order_prepared_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
