# Generated by Django 3.1.4 on 2021-04-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('pre_order', '0007_auto_20210203_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.warehouse'),
        ),
    ]
