# Generated by Django 3.1.4 on 2021-08-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0009_stocklog_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannedbarcode',
            name='scanning_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
