# Generated by Django 3.1.4 on 2021-09-07 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pre_order', '0010_auto_20210809_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='support@bondstein.com', max_length=254, unique=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='item',
            field=models.ManyToManyField(related_name='suppliers_item', to='pre_order.Item'),
        ),
    ]
