# Generated by Django 3.1.4 on 2021-09-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0011_auto_20210907_0345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='created_by',
            new_name='added_by',
        ),
    ]
