# Generated by Django 3.1.4 on 2021-01-23 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0003_auto_20210118_0327'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=30, unique=True)),
                ('challan_amount', models.IntegerField()),
                ('challan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_stock_out', models.BooleanField(default=0)),
                ('is_deleted', models.BooleanField(default=0)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responsible_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.responsibleperson')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.warehouse')),
            ],
            options={
                'db_table': 'challans',
            },
        ),
        migrations.CreateModel(
            name='ChallanDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('challan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.challan')),
                ('item_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_order.itemdetails')),
            ],
            options={
                'db_table': 'challan_details',
            },
        ),
    ]
