# Generated by Django 3.1.4 on 2021-01-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_challan_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='challandetails',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
