# Generated by Django 3.1.4 on 2021-01-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_challan_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='challan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challandetails',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
