# Generated by Django 3.1.4 on 2021-02-06 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '__first__'),
        ('pre_order', '0007_auto_20210203_0549'),
        ('inventory', '0007_auto_20210206_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='is_warehouse_out',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_status',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='sodetails',
            name='barcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_order.barcode'),
        ),
        migrations.CreateModel(
            name='STChallan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('challan_no', models.CharField(max_length=30, unique=True)),
                ('is_warehouse_out', models.BooleanField(default=0)),
                ('is_received', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_warehouse', to='users.warehouse')),
                ('to_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_warehouse', to='users.warehouse')),
            ],
            options={
                'db_table': 'stock_transfer_challans',
            },
        ),
        migrations.CreateModel(
            name='STCDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_order.barcode')),
                ('item_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_order.itemdetails')),
                ('stc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stchallan')),
            ],
            options={
                'db_table': 'stc_details',
            },
        ),
    ]
