# Generated by Django 3.1.4 on 2021-04-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pre_order', '0007_auto_20210203_0549'),
        ('inventory', '0008_auto_20210207_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='STCBarcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pre_order.barcode')),
                ('stcd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stcdetails')),
            ],
            options={
                'db_table': 'stc_barcodes',
            },
        ),
    ]
