# Generated by Django 3.1.4 on 2021-04-24 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210424_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='floatingsalesdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
