# Generated by Django 3.1.4 on 2021-09-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_channeldemanddetails_final_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channeldemand',
            name='final_demand',
        ),
    ]
